import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/styles.css";
import "@/styles/table.css";
import "@/styles/animation.css";
import { AuthProvider } from "@/hooks/use-auth";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/AppSidebar";
import { Toaster } from "@/components/ui/toaster";
import { AppCanvas } from "@/components/shared/AppCanvas";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SidebarProvider className="bg-slate-100 max-w-[2560px] mx-auto">
            <AppSidebar />
            <Toaster position="top-center" />
            <AppCanvas children={ children } />
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
